### ISSUE TITLE
ending games

### ISSUE THREAD

**Issue by ItsSammyM** [mafia-rust/mafia#264]
Ending a game to start a new one, 
There should be an inbetween screen stating who won, everyones roles, and wheather or not you won. Possible other stats>
^ If not that information could be placed somewhere on the (already crowded) lobby screen
The settings should keep between the games too so you can play again with the same settings. 

Host is also currently saved in two spots during the game. That should be fixed, so this way it knows where to get host from when you go back to lobby

**Comment by Jack-Papel** [comment]
I think this is resolved.
