### ISSUE TITLE
Team + EndgameCondition rework

### ISSUE THREAD

**Issue by ItsSammyM** [mafia-rust/mafia#299]
Mafia and coven are made into one faction.

If the faction has no Godfather or Mafioso, they are given the necronomicon on night 3.

Exclude either Godfather+Mafioso(Mafia Killing) or Mafia Power to make sure there are no stacked teams
Godfather Medusa HexMaster Witch Shouldnt be possible

Make one team struct. Each team contains this data: Necronomicon and Vampire list.

Teams are identified by number. Town is team 0, mafia is team 1 usually. This will allow us to put any role on any team. Roles will then have default teams.

Jester dafaults to no team.

Endgame Condition will be removed.
The game ends when there is 1 team remaining.

--------------------------

Hypothetically, Just have roles and they default to certain teams but you can decide what team their on in the rolelist in lobby.

**Comment by Jack-Papel** [comment]
Out of date, should be remade
