### ISSUE TITLE
Keyword context

### ISSUE THREAD

**Issue by Jack-Papel** [mafia-rust/mafia#304]
- [x] Create a simple page location system that can be parsed to locate a specific wiki page. Something like `/role/mafioso` or `/article/phases_and_timelines`
- [x] Maybe let the standalone wiki page use this in its URL? e.g. `localhost:3000/wiki/role/mafioso`
- [x] Let keywords specify a page location
- [x] Clicking on a keyword should open the wiki to the corresponding page, if one exists.
  - [x] Keywords should act as buttons, but not look like buttons. Decide on a style that indicates the text is clickable but doesn't make it look like a UI element. Maybe an underline or a hover color?
  - [x] Make sure keywords without wiki links still look normal
  - [x] Decide whether links should be determined before or after text correction
  - [x] Ensure this doesn't break wiki history
- [x] Add an `allowWikiLinks` prop to the StyledText component which is defaulted to true (e.g., the wiki buttons don't need to have wiki links).

**Comment by TB516** [comment]
This issue was marked as completed but the feature hasn't been implemented. Would we be able to reopen this issue until it has been properly resolved?

**Comment by Jack-Papel** [comment]
I'll open a new issue, since this was completed and has since become undone
