### ISSUE TITLE
Create keyword variants

### ISSUE THREAD

**Issue by Jack-Papel** [mafia-rust/mafia#468]
In the lang file, add variants for keywords. For example:
For the keyword 
```json
"keyword.jail": "Jail"
```
allow variants such as 
```json
"keyword.jail.var0": "Jailed"
"keyword.jail.var1": "Jailing"
```
that also automatically redirect to the same wiki page as the original when clicked

**Comment by Jack-Papel** [comment]
@ItsSammyM I want your thoughts on this

**Comment by ItsSammyM** [comment]
Make sure in keywords.json and other places where style text matters, it automatically adds all var0 var1.

Also make sure it works for every string in lang that gets coloured.

Make it so var0 is not necessary so I don't need to add var0 to the end of everything
