### ISSUE TITLE
Wiki article for 'good'

### ISSUE THREAD

**Issue by Jack-Papel** [mafia-rust/mafia#506]
Or redirect to Town wiki and specify that town == good

**Comment by emt7553** [comment]
More wiki changes needed
Trapper and jester articles need changing.
Change grant defense to protect
Re order bullet points in order of importance 
Create new section (overview, specifics) to group pages

**Comment by emt7553** [comment]
Change protection wiki, change veteran to protect themself

**Comment by emt7553** [comment]
All changes made.
