### ISSUE TITLE
hypnotize encyclopedia article

### ISSUE THREAD

**Issue by ItsSammyM** [mafia-rust/mafia#543]
hypnotize
hypnotized

the event of you getting a false message from a hypnotist

**Comment by emt7553** [comment]
I think with words like this, alert, frame etc. they should exist in ONLY the guide section where no further explanation is needed, just as a way for people to refer to the mechanic. They don't need to be keywords like doused does unless its something that matters more like if other roles could see if you were hypnotized or it lasted indefinitely or something.

**Comment by ItsSammyM** [comment]
Just have the article be one sentence.

It's important to have the article in the case that someone looks it up they get a response.

Just have it link to hypnotist.
If it is something that people will say, then I believe it should be an article
